"""Generate every FamilyApp icon asset from one vector definition.

The mark is the "soft house" from the icon workbench: a rounded navy house with
two lit windows and a red chimney on a sunflower background. Geometry lives in
the 108-unit grid of an Android adaptive icon, so the same numbers drive the SVG
source, Android vector drawables and the PNG exports.

Run with Python and Pillow installed:

    python app/scripts/export_brand_icons.py
"""
import math
from pathlib import Path

from PIL import Image, ImageDraw

APP = Path(__file__).resolve().parents[1]
BRAND = APP / "assets" / "branding"
RES = APP / "android" / "app" / "src" / "main" / "res"

GRID = 108
BACKGROUND = "#F6C445"
HOUSE = "#233656"
CHIMNEY = "#E8553E"
WINDOW = "#FFF1C9"

# The house is this convex pentagon grown by HOUSE_RADIUS, which rounds every
# corner. Its farthest point is ~35 units from the centre, inside the 36-unit
# circle that launchers keep visible.
HOUSE_CORE = [(54, 32.4), (74.4, 48), (74.4, 73.2), (33.6, 73.2), (33.6, 48)]
HOUSE_RADIUS = 7.2
# (left, top, right, bottom, corner radius); the chimney's bottom hides behind the roof.
CHIMNEY_RECT = (64.8, 27.6, 72.6, 42, 1.8)
WINDOW_RECTS = [(36, 56.4, 49.2, 69.6, 3), (58.8, 56.4, 72, 69.6, 3)]


def fmt(value):
    return f"{value:.3f}".rstrip("0").rstrip(".")


def house_path():
    """Outline of HOUSE_CORE offset by HOUSE_RADIUS (edges joined by arcs)."""
    points, r = HOUSE_CORE, HOUSE_RADIUS
    count = len(points)
    normals = []
    for i in range(count):
        (x1, y1), (x2, y2) = points[i], points[(i + 1) % count]
        length = math.hypot(x2 - x1, y2 - y1)
        # Points run clockwise on screen, so (dy, -dx) points outwards.
        normals.append(((y2 - y1) / length, -(x2 - x1) / length))
    parts = []
    for i, (x, y) in enumerate(points):
        nin, nout = normals[i - 1], normals[i]
        start = (x + r * nin[0], y + r * nin[1])
        end = (x + r * nout[0], y + r * nout[1])
        parts.append(("M" if i == 0 else "L") + f"{fmt(start[0])} {fmt(start[1])}")
        parts.append(f"A{fmt(r)} {fmt(r)} 0 0 1 {fmt(end[0])} {fmt(end[1])}")
    return " ".join(parts) + " Z"


def rounded_rect_path(left, top, right, bottom, r):
    return (
        f"M{fmt(left + r)} {fmt(top)} H{fmt(right - r)} "
        f"A{fmt(r)} {fmt(r)} 0 0 1 {fmt(right)} {fmt(top + r)} V{fmt(bottom - r)} "
        f"A{fmt(r)} {fmt(r)} 0 0 1 {fmt(right - r)} {fmt(bottom)} H{fmt(left + r)} "
        f"A{fmt(r)} {fmt(r)} 0 0 1 {fmt(left)} {fmt(bottom - r)} V{fmt(top + r)} "
        f"A{fmt(r)} {fmt(r)} 0 0 1 {fmt(left + r)} {fmt(top)} Z"
    )


def write_svg():
    windows = "".join(
        f'\n  <path fill="{WINDOW}" d="{rounded_rect_path(*rect)}"/>' for rect in WINDOW_RECTS
    )
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {GRID} {GRID}">\n'
        f'  <rect width="{GRID}" height="{GRID}" fill="{BACKGROUND}"/>\n'
        f'  <path fill="{CHIMNEY}" d="{rounded_rect_path(*CHIMNEY_RECT)}"/>\n'
        f'  <path fill="{HOUSE}" d="{house_path()}"/>'
        f"{windows}\n</svg>\n"
    )
    (BRAND / "familyapp-icon.svg").write_text(svg, encoding="utf-8")


def android_color(hex_color):
    return "#FF" + hex_color.lstrip("#").upper()


def vector_drawable(paths):
    body = "".join(
        f'\n    <path\n        android:fillColor="{color}"{extra}\n        android:pathData="{data}" />'
        for color, data, extra in paths
    )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by app/scripts/export_brand_icons.py; edit the script instead. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{GRID}dp"\n    android:height="{GRID}dp"\n'
        f'    android:viewportWidth="{GRID}"\n    android:viewportHeight="{GRID}">'
        f"{body}\n</vector>\n"
    )


def write_android_vectors():
    windows = [rounded_rect_path(*rect) for rect in WINDOW_RECTS]
    foreground = [
        (android_color(CHIMNEY), rounded_rect_path(*CHIMNEY_RECT), ""),
        (android_color(HOUSE), house_path(), ""),
        *[(android_color(WINDOW), data, "") for data in windows],
    ]
    # Themed icons use only the alpha channel, so windows become holes.
    monochrome = [
        ("#FFFFFFFF", rounded_rect_path(*CHIMNEY_RECT), ""),
        ("#FFFFFFFF", " ".join([house_path(), *windows]), '\n        android:fillType="evenOdd"'),
    ]
    drawable = RES / "drawable"
    (drawable / "ic_launcher_foreground.xml").write_text(vector_drawable(foreground), encoding="utf-8")
    (drawable / "ic_launcher_monochrome.xml").write_text(vector_drawable(monochrome), encoding="utf-8")


def render(size, supersample=4):
    """Rasterise the full-bleed icon with supersampling for smooth edges."""
    canvas = size * supersample
    scale = canvas / GRID
    image = Image.new("RGB", (canvas, canvas), BACKGROUND)
    draw = ImageDraw.Draw(image)

    def box(left, top, right, bottom, r):
        draw_args = [left * scale, top * scale, right * scale, bottom * scale]
        return draw_args, r * scale

    rect, radius = box(*CHIMNEY_RECT)
    draw.rounded_rectangle(rect, radius, fill=CHIMNEY)
    # Minkowski sum of the pentagon and a disc: fill, thick edges, round corners.
    core = [(x * scale, y * scale) for x, y in HOUSE_CORE]
    r = HOUSE_RADIUS * scale
    draw.polygon(core, fill=HOUSE)
    for i, start in enumerate(core):
        end = core[(i + 1) % len(core)]
        draw.line([start, end], fill=HOUSE, width=round(2 * r))
        draw.ellipse([start[0] - r, start[1] - r, start[0] + r, start[1] + r], fill=HOUSE)
    for window in WINDOW_RECTS:
        rect, radius = box(*window)
        draw.rounded_rectangle(rect, radius, fill=WINDOW)
    return image.resize((size, size), Image.Resampling.LANCZOS)


def export_pngs():
    targets = {
        BRAND / "familyapp-icon-1024.png": 1024,
        BRAND / "alice-icon-224.png": 224,
        APP / "web" / "favicon.png": 32,
        APP / "web" / "icons" / "Icon-192.png": 192,
        APP / "web" / "icons" / "Icon-512.png": 512,
        APP / "web" / "icons" / "Icon-maskable-192.png": 192,
        APP / "web" / "icons" / "Icon-maskable-512.png": 512,
    }
    # Legacy launchers (before Android 8) use these full-bleed squares.
    for density, size in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
        targets[RES / f"mipmap-{density}" / "ic_launcher.png"] = size
    for target, size in targets.items():
        target.parent.mkdir(parents=True, exist_ok=True)
        render(size).save(target, optimize=True)
        with Image.open(target) as check:
            assert check.size == (size, size) and check.mode == "RGB"
    return len(targets)


def export():
    write_svg()
    write_android_vectors()
    count = export_pngs()
    print(f"Wrote the SVG source, 2 Android vector drawables and {count} opaque PNG icons.")


if __name__ == "__main__":
    export()
